name: Iowajeeper
favicon: null
layout_spectrum: 0.8991779321804643
typography_spectrum: 0.5857960518915206
title: Iowa Jeeper
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#838594'
    - '#fefefe'
    - '#d5d3d6'
    - '#3c2a1c'
  brandStrength: 0.2984125455841422
  lightness: 0.8425970992539078
  saturation: 0.7363290551584214
  rhythmicContrast: 0.15876523382030427
purpose: []
